// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Subcommand;
use ika_config::{IKA_SUI_CONFIG, ika_config_dir};
use ika_types::messages_dwallet_mpc::IkaNetworkConfig;
use serde::Deserialize;
use sui_config::{Config as SuiConfig, SUI_CLIENT_CONFIG, SUI_KEYSTORE_FILENAME, sui_config_dir};
use sui_keys::keystore::{FileBasedKeystore, Keystore};
use sui_sdk::sui_client_config::{SuiClientConfig, SuiEnv};
use sui_types::base_types::ObjectID;

use crate::IkaPackagesConfigFile;

const GITHUB_RAW_BASE: &str =
    "https://raw.githubusercontent.com/dwallet-labs/ika/main/deployed_contracts";

/// Known Sui RPC URLs per network.
fn sui_rpc_url(network: &str) -> &'static str {
    match network {
        "mainnet" => "https://fullnode.mainnet.sui.io:443",
        "testnet" => "https://fullnode.testnet.sui.io:443",
        _ => "http://127.0.0.1:9000",
    }
}

/// Map a bare network name to the Ika-prefixed Sui env alias.
fn ika_env_alias(network: &str) -> String {
    format!("ika-{network}")
}

/// Networks whose contract addresses are fetched from GitHub.
/// Localnet is excluded because its addresses are generated locally.
const REMOTE_NETWORKS: &[&str] = &["testnet", "mainnet"];

/// All networks that get a Sui CLI environment (including localnet).
const ALL_NETWORKS: &[&str] = &["testnet", "mainnet", "localnet"];

/// Config management commands.
#[derive(Subcommand)]
#[clap(rename_all = "kebab-case")]
pub enum IkaConfigCommand {
    /// Initialize Ika CLI config by fetching deployed contract addresses from GitHub
    /// and creating Sui CLI environments (ika-mainnet, ika-testnet, ika-localnet).
    ///
    /// Fetches the address.yaml for testnet and mainnet, writes the
    /// ika_sui_config.yaml used by all dwallet commands, and adds Sui CLI environments
    /// for all networks including localnet.
    #[clap(name = "init")]
    Init {
        /// Output path for the Ika config file.
        #[clap(long)]
        output: Option<PathBuf>,
    },

    /// Add or update a network environment from a local ika_config.json file.
    ///
    /// Use this to configure localnet (or any custom network) from the
    /// ika_config.json generated by `ika system initialize` or `ika-swarm-config`.
    #[clap(name = "add-env")]
    AddEnv {
        /// Network name (e.g., `localnet`, `devnet`). Stored as `ika-{name}`.
        #[clap(long)]
        network: String,
        /// Path to the ika_config.json file containing contract addresses.
        #[clap(long)]
        from_file: PathBuf,
        /// Sui RPC URL for this environment.
        #[clap(long)]
        rpc: Option<String>,
        /// Path to the Ika config file to update.
        #[clap(long)]
        config: Option<PathBuf>,
    },

    /// Re-fetch deployed contract addresses from GitHub for the specified networks
    /// and update the existing Ika config file.
    #[clap(name = "sync")]
    Sync {
        /// Networks to sync (comma-separated). Default: `testnet,mainnet`.
        #[clap(long, value_delimiter = ',', default_value = "testnet,mainnet")]
        network: Vec<String>,
        /// Path to the Ika config file to update.
        #[clap(long)]
        config: Option<PathBuf>,
    },

    /// Show the current Ika CLI config.
    #[clap(name = "show")]
    Show {
        /// Path to the config file.
        #[clap(long)]
        config: Option<PathBuf>,
    },
}

/// Raw address.yaml structure from deployed_contracts/{network}/address.yaml.
#[derive(Debug, Deserialize)]
struct DeployedAddresses {
    ika_package_id: String,
    ika_common_package_id: String,
    ika_dwallet_2pc_mpc_package_id: String,
    ika_system_package_id: String,
    ika_system_object_id: String,
    ika_coordinator_object_id: String,
    #[serde(default)]
    ika_dwallet_2pc_mpc_package_id_v2: Option<String>,
    #[serde(default)]
    ika_system_package_id_v2: Option<String>,
}

impl DeployedAddresses {
    fn to_network_config(&self) -> Result<IkaNetworkConfig> {
        // Use v2 package IDs if available, otherwise fall back to v1
        let dwallet_2pc_mpc_id = self
            .ika_dwallet_2pc_mpc_package_id_v2
            .as_deref()
            .unwrap_or(&self.ika_dwallet_2pc_mpc_package_id);
        let system_id = self
            .ika_system_package_id_v2
            .as_deref()
            .unwrap_or(&self.ika_system_package_id);

        Ok(IkaNetworkConfig::new(
            parse_object_id(&self.ika_package_id)?,
            parse_object_id(&self.ika_common_package_id)?,
            parse_object_id(dwallet_2pc_mpc_id)?,
            None,
            parse_object_id(system_id)?,
            parse_object_id(&self.ika_system_object_id)?,
            parse_object_id(&self.ika_coordinator_object_id)?,
        ))
    }
}

fn parse_object_id(s: &str) -> Result<ObjectID> {
    s.parse().with_context(|| format!("Invalid object ID: {s}"))
}

/// Fetch addresses from GitHub for the given networks and return the env map.
async fn fetch_network_configs(networks: &[String]) -> Result<HashMap<String, IkaNetworkConfig>> {
    let mut envs: HashMap<String, IkaNetworkConfig> = HashMap::new();

    for net in networks {
        let url = format!("{GITHUB_RAW_BASE}/{net}/address.yaml");
        println!("Fetching {net} config from {url}");

        let body = reqwest::get(&url)
            .await
            .with_context(|| format!("Failed to fetch {url}"))?
            .text()
            .await
            .with_context(|| format!("Failed to read response from {url}"))?;

        let addresses: DeployedAddresses = serde_yaml::from_str(&body)
            .with_context(|| format!("Failed to parse address.yaml for {net}"))?;

        let config = addresses.to_network_config()?;
        let alias = ika_env_alias(net);
        envs.insert(alias.clone(), config);
        println!(
            "  Configured as Sui env: {alias} (RPC: {})",
            sui_rpc_url(net)
        );
    }

    Ok(envs)
}

/// Write the Ika config file to disk.
fn write_ika_config(path: &PathBuf, config_file: &IkaPackagesConfigFile) -> Result<()> {
    let yaml = serde_yaml::to_string(config_file).context("Failed to serialize config")?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, format!("---\n{yaml}"))
        .with_context(|| format!("Failed to write config to {path:?}"))?;
    Ok(())
}

/// Add Sui CLI environments for the given networks.
fn add_sui_envs(networks: &[String], sui_config_path: &PathBuf) -> Result<()> {
    let mut sui_config = SuiClientConfig::load(sui_config_path).unwrap_or_else(|_| {
        // Create a new config with a file-based keystore next to the config file.
        let keystore_path = sui_config_path
            .parent()
            .map(|p| p.join(SUI_KEYSTORE_FILENAME))
            .unwrap_or_else(|| PathBuf::from(SUI_KEYSTORE_FILENAME));
        let keystore = Keystore::File(
            FileBasedKeystore::load_or_create(&keystore_path).expect("Failed to create keystore"),
        );
        SuiClientConfig::new(keystore)
    });

    for net in networks {
        let alias = ika_env_alias(net);
        let rpc = sui_rpc_url(net).to_string();

        if sui_config.get_env(&Some(alias.clone())).is_some() {
            println!("  Sui env '{alias}' already exists, skipping");
            continue;
        }

        sui_config.add_env(SuiEnv {
            alias: alias.clone(),
            rpc: rpc.clone(),
            ws: None,
            basic_auth: None,
            chain_id: None,
        });
        println!("  Created Sui env: {alias} -> {rpc}");
    }

    sui_config.persisted(sui_config_path).save()?;
    Ok(())
}

fn default_ika_config_path() -> PathBuf {
    ika_config_dir()
        .unwrap_or_else(|_| PathBuf::from("."))
        .join(IKA_SUI_CONFIG)
}

/// Load an existing Ika config file, or return an empty one.
fn load_ika_config(path: &PathBuf) -> Result<IkaPackagesConfigFile> {
    if path.exists() {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("Cannot read {}", path.display()))?;
        serde_yaml::from_str(&content).with_context(|| "Failed to parse existing config")
    } else {
        Ok(IkaPackagesConfigFile {
            envs: HashMap::new(),
        })
    }
}

impl IkaConfigCommand {
    pub async fn execute(self, client_config: Option<PathBuf>) -> Result<()> {
        match self {
            IkaConfigCommand::Init { output } => {
                let output_path = output.unwrap_or_else(default_ika_config_path);
                let remote: Vec<String> = REMOTE_NETWORKS.iter().map(|s| s.to_string()).collect();
                let all: Vec<String> = ALL_NETWORKS.iter().map(|s| s.to_string()).collect();

                // Fetch contract addresses from GitHub for remote networks.
                let envs = fetch_network_configs(&remote).await?;
                let config_file = IkaPackagesConfigFile { envs };
                write_ika_config(&output_path, &config_file)?;
                println!("\nIka config written to: {}", output_path.display());

                // Create Sui CLI environments for all networks (including localnet).
                let sui_config_path =
                    client_config.unwrap_or(sui_config_dir()?.join(SUI_CLIENT_CONFIG));
                add_sui_envs(&all, &sui_config_path)?;

                println!(
                    "\nNext steps:\n\
                     1. Switch to an Ika environment: sui client switch --env ika-testnet\n\
                     2. For localnet, add config: ika config add-env --network localnet --from-file ika_config.json\n\
                     3. Ensure you have SUI tokens for gas and IKA tokens for operations"
                );
                Ok(())
            }

            IkaConfigCommand::AddEnv {
                network,
                from_file,
                rpc,
                config,
            } => {
                let config_path = config.unwrap_or_else(default_ika_config_path);
                let alias = ika_env_alias(&network);

                // Read the ika_config.json file.
                let content = std::fs::read_to_string(&from_file)
                    .with_context(|| format!("Cannot read config file: {}", from_file.display()))?;
                let network_config: IkaNetworkConfig = serde_json::from_str(&content)
                    .with_context(|| {
                        format!(
                            "Failed to parse {} as IkaNetworkConfig",
                            from_file.display()
                        )
                    })?;

                // Load existing Ika config and insert/update the env.
                let mut config_file = load_ika_config(&config_path)?;
                config_file.envs.insert(alias.clone(), network_config);
                write_ika_config(&config_path, &config_file)?;
                println!(
                    "Added env '{alias}' from {} to {}",
                    from_file.display(),
                    config_path.display()
                );

                // Also create/update the Sui CLI env if an RPC was given or we know it.
                let rpc_url = rpc.unwrap_or_else(|| sui_rpc_url(&network).to_string());
                let sui_config_path = sui_config_dir()?.join(SUI_CLIENT_CONFIG);
                add_sui_envs(&[network], &sui_config_path)?;
                println!("  RPC: {rpc_url}");

                Ok(())
            }

            IkaConfigCommand::Sync { network, config } => {
                let config_path = config.unwrap_or_else(default_ika_config_path);

                // Load existing config (or start fresh).
                let mut config_file = load_ika_config(&config_path)?;

                // Fetch and merge updated addresses.
                let new_envs = fetch_network_configs(&network).await?;
                config_file.envs.extend(new_envs);

                write_ika_config(&config_path, &config_file)?;
                println!("\nIka config synced at: {}", config_path.display());
                Ok(())
            }

            IkaConfigCommand::Show { config } => {
                let config_path = config.unwrap_or_else(default_ika_config_path);

                let content = std::fs::read_to_string(&config_path).with_context(|| {
                    format!(
                        "Cannot read config at {}. Run 'ika config init' first.",
                        config_path.display()
                    )
                })?;
                println!("{content}");
                Ok(())
            }
        }
    }
}
