// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear

#![allow(warnings)]
//! Encrypt program Rust client.
//!
//! Generated by Codama from the program IDL.
//! Run `npm run generate-clients` to regenerate.

// Generated code will be placed in src/generated/ by Codama
// Re-export generated code
pub mod generated;
pub use generated::*;

// gRPC client for the Encrypt executor service
pub mod grpc;

// Re-export commonly used items
pub use generated::accounts::*;
pub use generated::errors::*;
pub use generated::programs::*;
