// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import * as fs from 'fs';
import * as path from 'path';
import { createEncryptCodamaBuilder } from './lib/encrypt-codama-builder';

const solanaDir = path.resolve(__dirname, '..');
const idlDir = path.join(solanaDir, 'idl');
const rustClientsDir = path.join(solanaDir, 'clients', 'rust');
const typescriptClientsDir = path.join(solanaDir, 'clients', 'typescript');

// Read IDL generated by build.rs
const idlPath = path.join(idlDir, 'encrypt_program.json');
if (!fs.existsSync(idlPath)) {
  console.error(
    'IDL not found. Run `npm run generate-idl` first (cargo check --features idl).',
  );
  process.exit(1);
}

const idlJson = JSON.parse(fs.readFileSync(idlPath, 'utf-8'));

// Build Codama AST with transformations
const codama = createEncryptCodamaBuilder(idlJson)
  .appendAccountDiscriminator()
  .appendPdaDerivers()
  .setInstructionAccountDefaultValues()
  .updateInstructionBumps()
  .build();

// Render Rust client
async function renderClients() {
  const { renderVisitor: renderRustVisitor } = await import('@codama/renderers-rust');
  const { renderVisitor: renderJsVisitor } = await import('@codama/renderers-js');

  codama.accept(
    renderRustVisitor(rustClientsDir, {
      deleteFolderBeforeRendering: true,
      formatCode: true,
    }),
  );
  console.log('Rust client generated at clients/rust/src/generated/');

  await codama.accept(
    renderJsVisitor(typescriptClientsDir, {
      deleteFolderBeforeRendering: true,
      formatCode: true,
    }),
  );
  console.log('TypeScript client generated at clients/typescript/src/generated/');
}

renderClients()
  .then(() => generateGrpcClient())
  .catch((err) => {
    console.error('Client generation failed:', err);
    process.exit(1);
  });

// Generate static gRPC TypeScript client from proto
async function generateGrpcClient() {
  const { execFileSync } = await import('child_process');
  const rootDir = path.resolve(solanaDir, '../..');
  const outDir = path.join(typescriptClientsDir, 'src', 'generated', 'grpc');
  fs.mkdirSync(outDir, { recursive: true });

  execFileSync('protoc', [
    `--plugin=${rootDir}/node_modules/.bin/protoc-gen-ts_proto`,
    `--ts_proto_out=${outDir}`,
    '--ts_proto_opt=outputServices=grpc-js',
    '--ts_proto_opt=esModuleInterop=true',
    '--ts_proto_opt=env=node',
    `--proto_path=${rootDir}/proto`,
    'encrypt_service.proto',
  ], { stdio: 'inherit' });
  console.log('gRPC TypeScript client generated at clients/typescript/src/generated/grpc/');
}
