# Checks formatting in all move contracts
# Uses a fixed NPM version to separate prettier-move release changes from system package
# changes.
#
# With new releases of prettier-move, update the `VERSION` in the env.
name: Move Formatter

on:
  push:
    branches: [main, dev]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

env:
  VERSION: 0.3.5

jobs:
  prettier-move:
    name: Check Move formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - contracts/ika # ika token package
          - contracts/ika_common # ika common package
          - contracts/ika_dwallet_2pc_mpc # ika dwallet 2pc mpc package
          - contracts/ika_system # ika system package
          - contracts/dwallet_utils # dwallet utils package
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npx -p @mysten/prettier-plugin-move@${{ env.VERSION }} prettier-move -c **/*.move
